# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import yksi.custom_storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('photo', models.FileField(blank=True, null=True, upload_to='candidate-photos')),
                ('secure_photo', models.FileField(blank=True, null=True, storage=yksi.custom_storages.SecureStorage(), upload_to='candidate-photos-secure')),
            ],
        ),
    ]
