"""
Django settings for yksi project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import json
import environ
import dj_database_url

env = environ.Env(DEBUG=(bool, False),)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third pary apps
    'crispy_forms',
    'storages',
    'django_cleanup',
    'rest_framework',
    'social.apps.django_app.default',
    'captcha',
    # my apps
    'newsletter',
    'candidate',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

# Authentication backends Setting
AUTHENTICATION_BACKENDS = (
    # For Facebook Authentication
    #'social.backends.facebook.FacebookOAuth2',

    # For Twitter Authentication
    'social.backends.twitter.TwitterOAuth',

    # For Google Authentication
    #'social.backends.google.GoogleOpenId',
    'social.backends.google.GoogleOAuth2',
    #'social.backends.google.GoogleOAuth',

    # Default Django Auth Backends
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'yksi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Setting of Template Context Processors for Social Auth
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'yksi.wsgi.application'



# django-environ does not work with Pivotal Web Services and MySQL
# DATABASES = {
#     'default': env.db(), # Raises ImproperlyConfigured exception if DATABASE_URL not in os.environ
# }
DATABASES = {'default': dj_database_url.config()}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# Celery settings
cloudamqp = json.loads(os.environ['VCAP_SERVICES'])['cloudamqp']
for creds in cloudamqp:
    if "rabbitmq" in creds['name']:
        BROKER_URL = creds['credentials']['uri']

#: Only add pickle to this list if your broker is secured
#: from unwanted access (see userguide/security.html)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# https://www.cloudamqp.com/docs/celery.html
BROKER_POOL_LIMIT = 1 # Will decrease connection usage
BROKER_HEARTBEAT = 30 # Will detect stale connections faster
BROKER_CONNECTION_TIMEOUT = 30 # May require a long timeout due to Linux DNS timeouts etc
CELERY_RESULT_BACKEND = None
CELERY_SEND_EVENTS = False # Will not create celeryev.* queues
CELERY_EVENT_QUEUE_EXPIRES = 60 # Will delete all celeryev. queues without consumers after 1 minute.

# add S3 compatible storge
STATICFILES_STORAGE = 'yksi.custom_storages.StaticStorage'
DEFAULT_FILE_STORAGE = 'yksi.custom_storages.MediaStorage'

# load user provided services
userservices = json.loads(os.environ['VCAP_SERVICES'])['user-provided']
for configs in userservices:
    if "ecs" in configs['name']:
        AWS_S3_HOST = configs['credentials']['HOST']
        AWS_ACCESS_KEY_ID = configs['credentials']['ACCESS_KEY_ID']
        AWS_SECRET_ACCESS_KEY = configs['credentials']['SECRET_ACCESS_KEY']
        S3_PUBLIC_URL = configs['credentials']['PUBLIC_URL']
    elif "mail" in configs['name']:
        EMAIL_HOST = configs['credentials']['HOST']
        EMAIL_HOST_USER = configs['credentials']['USER']
        EMAIL_HOST_PASSWORD = configs['credentials']['PASSWORD']
        EMAIL_PORT = int(configs['credentials']['PORT'])
        if configs['credentials']['TLS'] == 'True':
            EMAIL_USE_TLS = True
        else:
            EMAIL_USE_TLS = False
    elif "socialauth" in configs['name']:
        SOCIAL_AUTH_TWITTER_KEY = configs['credentials']['TWITTER_KEY']
        SOCIAL_AUTH_TWITTER_SECRET = configs['credentials']['TWITTER_SECRET']
        SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = configs['credentials']['GOOGLE_KEY']
        SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = configs['credentials']['GOOGLE_SECRET']

AWS_AUTO_CREATE_BUCKET = True
AWS_S3_SECURE_URLS = False
AWS_QUERYSTRING_AUTH = False

STATIC_BUCKET_NAME = 'static'
STATIC_CUSTOM_DOMAIN = '%s.%s' %(STATIC_BUCKET_NAME,S3_PUBLIC_URL)
STATIC_URL = "http://%s/" % STATIC_CUSTOM_DOMAIN

MEDIA_BUCKET_NAME = 'media'
MEDIA_CUSTOM_DOMAIN = '%s.%s' %(MEDIA_BUCKET_NAME,S3_PUBLIC_URL)
MEDIA_URL = "http://%s/" % MEDIA_CUSTOM_DOMAIN

SECURE_BUCKET_NAME = 'secure'


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static_custom'),
)

CRISPY_TEMPLATE_PACK = 'bootstrap3'
CRISPY_FAIL_SILENTLY = not DEBUG

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    'PAGE_SIZE': 10
}

CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
