# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import mytwitter.models
import uuid
import yksi.custom_storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('text', models.TextField(max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=15)),
                ('screenname', models.CharField(blank=True, max_length=20)),
                ('from_twitter', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TweetPic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(storage=yksi.custom_storages.SecureStorage(), upload_to=mytwitter.models.TweetPictureName)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='mytwitter.Tweet')),
            ],
        ),
    ]
