# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytwitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
