# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytwitter', '0002_auto_20151222_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='from_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
