# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytwitter', '0003_tweet_from_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=160),
        ),
    ]
