# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytwitter', '0005_auto_20151223_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='screenname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
